global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: spring-stub
    static_configs:
      - targets: ["stub:8080"]
    metrics_path: /actuator/prometheus

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
    metric_relabel_configs:
      # Drop all pushgateway internal metrics
      - source_labels: [__name__]
        regex: 'pushgateway_.*|go_.*|process_.*|promhttp_.*'
        action: drop
