gatling {
  core {
    directory {
      results = "build/reports/gatling"
    }
  }
  charting {
    indicators {
      lowerBound = 800
      higherBound = 1200
      percentile1 = 50
      percentile2 = 75
      percentile3 = 95
      percentile4 = 99
    }
  }
  data {
    writers = [console, file, graphite]
    graphite {
      host = ${?GRAPHITE_HOST}
      host = "localhost"
      port = ${?GRAPHITE_PORT}
      port = 9109
      protocol = "tcp"
      rootPathPrefix = "gatling"
      bufferSize = 8192
    }
  }
}
